spring:
  application:
    name: manage_activities
  
  # Primary DataSource (EC2)
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      
  # Fallback DataSource (Localhost)
  datasource-fallback:
    url: ${DB_FALLBACK_URL}
    username: ${DB_FALLBACK_USERNAME}
    password: ${DB_FALLBACK_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  valid-duration: ${JWT_VALID_DURATION:3600}